[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "wexample-filestate-python"
version = "0.0.36"
description = "Helpers for Python."
authors = [
    { name = "weeger", email = "contact@wexample.com" },
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "autoflake",
    "flynt", # filestate: keep
    "pydantic>=2,<3",
    "python-dotenv",
    "pyupgrade",
    "wexample-filestate-dev",
    "wexample-filestate-git",
    "tomlkit"
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/wexample/python-filestate-python"

[project.optional-dependencies]
dev = ["pytest"]

[tool.pdm.build]
includes = ["python_package_workdir/py.typed"]
